language: en

pipeline:
  - name: WhitespaceTokenizer
  # - name: RegexEntityExtractor
  - name: RegexFeaturizer
    use_lookup_tables: True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
#     model_confidence: cosine
#   - name: RulePolicy

rest:
  #lol